server:
  port: 80
#为防止报错
spring:
  application:
    name: Consumer_Feign
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true  # 数据库名称
    username: root
    password: 216918
#
eureka:
  client:
  # 客户端注册进eureka服务列表内
    service-url:
      #      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka
      #设置此形式需要去hosts文件修改路径映射
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #不使用默认的名字 改成我们自己定义的
    instance-id: Consumer80
    # 访问路径可以显示IP地址
    prefer-ip-address: true